package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alunos generated by hbm2java
 */
public class Alunos  implements java.io.Serializable {


     private Integer idAlunos;
     private Endereco endereco;
     private Planos planos;
     private Statusgeral statusgeral;
     private String nomeCompleto;
     private String apelido;
     private Date dataDeNascimento;
     private String rg;
     private String cpf;
     private Boolean responsavel;
     private String nomeResponsavel;
     private String telefoneContato;
     private String telefoneEmergencia;
     private String contatoEmergencia;
     private String email;
     private Boolean atestadoMedico;
     private int diaVencimento;
     private String numero;
     private String complemento;
     private byte[] foto;
     private Set modalidadescontratadases = new HashSet(0);

    public Alunos() {
    }

	
    public Alunos(Endereco endereco, Planos planos, Statusgeral statusgeral, String nomeCompleto, Date dataDeNascimento, String rg, String cpf, String telefoneContato, String telefoneEmergencia, String contatoEmergencia, String email, int diaVencimento, String numero) {
        this.endereco = endereco;
        this.planos = planos;
        this.statusgeral = statusgeral;
        this.nomeCompleto = nomeCompleto;
        this.dataDeNascimento = dataDeNascimento;
        this.rg = rg;
        this.cpf = cpf;
        this.telefoneContato = telefoneContato;
        this.telefoneEmergencia = telefoneEmergencia;
        this.contatoEmergencia = contatoEmergencia;
        this.email = email;
        this.diaVencimento = diaVencimento;
        this.numero = numero;
    }
    public Alunos(Endereco endereco, Planos planos, Statusgeral statusgeral, String nomeCompleto, String apelido, Date dataDeNascimento, String rg, String cpf, Boolean responsavel, String nomeResponsavel, String telefoneContato, String telefoneEmergencia, String contatoEmergencia, String email, Boolean atestadoMedico, int diaVencimento, String numero, String complemento, byte[] foto, Set modalidadescontratadases) {
       this.endereco = endereco;
       this.planos = planos;
       this.statusgeral = statusgeral;
       this.nomeCompleto = nomeCompleto;
       this.apelido = apelido;
       this.dataDeNascimento = dataDeNascimento;
       this.rg = rg;
       this.cpf = cpf;
       this.responsavel = responsavel;
       this.nomeResponsavel = nomeResponsavel;
       this.telefoneContato = telefoneContato;
       this.telefoneEmergencia = telefoneEmergencia;
       this.contatoEmergencia = contatoEmergencia;
       this.email = email;
       this.atestadoMedico = atestadoMedico;
       this.diaVencimento = diaVencimento;
       this.numero = numero;
       this.complemento = complemento;
       this.foto = foto;
       this.modalidadescontratadases = modalidadescontratadases;
    }
   
    public Integer getIdAlunos() {
        return this.idAlunos;
    }
    
    public void setIdAlunos(Integer idAlunos) {
        this.idAlunos = idAlunos;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Planos getPlanos() {
        return this.planos;
    }
    
    public void setPlanos(Planos planos) {
        this.planos = planos;
    }
    public Statusgeral getStatusgeral() {
        return this.statusgeral;
    }
    
    public void setStatusgeral(Statusgeral statusgeral) {
        this.statusgeral = statusgeral;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public Date getDataDeNascimento() {
        return this.dataDeNascimento;
    }
    
    public void setDataDeNascimento(Date dataDeNascimento) {
        this.dataDeNascimento = dataDeNascimento;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Boolean getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(Boolean responsavel) {
        this.responsavel = responsavel;
    }
    public String getNomeResponsavel() {
        return this.nomeResponsavel;
    }
    
    public void setNomeResponsavel(String nomeResponsavel) {
        this.nomeResponsavel = nomeResponsavel;
    }
    public String getTelefoneContato() {
        return this.telefoneContato;
    }
    
    public void setTelefoneContato(String telefoneContato) {
        this.telefoneContato = telefoneContato;
    }
    public String getTelefoneEmergencia() {
        return this.telefoneEmergencia;
    }
    
    public void setTelefoneEmergencia(String telefoneEmergencia) {
        this.telefoneEmergencia = telefoneEmergencia;
    }
    public String getContatoEmergencia() {
        return this.contatoEmergencia;
    }
    
    public void setContatoEmergencia(String contatoEmergencia) {
        this.contatoEmergencia = contatoEmergencia;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getAtestadoMedico() {
        return this.atestadoMedico;
    }
    
    public void setAtestadoMedico(Boolean atestadoMedico) {
        this.atestadoMedico = atestadoMedico;
    }
    public int getDiaVencimento() {
        return this.diaVencimento;
    }
    
    public void setDiaVencimento(int diaVencimento) {
        this.diaVencimento = diaVencimento;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getModalidadescontratadases() {
        return this.modalidadescontratadases;
    }
    
    public void setModalidadescontratadases(Set modalidadescontratadases) {
        this.modalidadescontratadases = modalidadescontratadases;
    }




}


