package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DespesaspagasAcademiaId generated by hbm2java
 */
public class DespesaspagasAcademiaId  implements java.io.Serializable {


     private int idDespesas;
     private Date dataDePagamentoDespesas;

    public DespesaspagasAcademiaId() {
    }

    public DespesaspagasAcademiaId(int idDespesas, Date dataDePagamentoDespesas) {
       this.idDespesas = idDespesas;
       this.dataDePagamentoDespesas = dataDePagamentoDespesas;
    }
   
    public int getIdDespesas() {
        return this.idDespesas;
    }
    
    public void setIdDespesas(int idDespesas) {
        this.idDespesas = idDespesas;
    }
    public Date getDataDePagamentoDespesas() {
        return this.dataDePagamentoDespesas;
    }
    
    public void setDataDePagamentoDespesas(Date dataDePagamentoDespesas) {
        this.dataDePagamentoDespesas = dataDePagamentoDespesas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DespesaspagasAcademiaId) ) return false;
		 DespesaspagasAcademiaId castOther = ( DespesaspagasAcademiaId ) other; 
         
		 return (this.getIdDespesas()==castOther.getIdDespesas())
 && ( (this.getDataDePagamentoDespesas()==castOther.getDataDePagamentoDespesas()) || ( this.getDataDePagamentoDespesas()!=null && castOther.getDataDePagamentoDespesas()!=null && this.getDataDePagamentoDespesas().equals(castOther.getDataDePagamentoDespesas()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDespesas();
         result = 37 * result + ( getDataDePagamentoDespesas() == null ? 0 : this.getDataDePagamentoDespesas().hashCode() );
         return result;
   }   


}


