package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1



/**
 * ModalidadescontratadasId generated by hbm2java
 */
public class ModalidadescontratadasId  implements java.io.Serializable {


     private int idModalidade;
     private int idAluno;

    public ModalidadescontratadasId() {
    }

    public ModalidadescontratadasId(int idModalidade, int idAluno) {
       this.idModalidade = idModalidade;
       this.idAluno = idAluno;
    }
   
    public int getIdModalidade() {
        return this.idModalidade;
    }
    
    public void setIdModalidade(int idModalidade) {
        this.idModalidade = idModalidade;
    }
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModalidadescontratadasId) ) return false;
		 ModalidadescontratadasId castOther = ( ModalidadescontratadasId ) other; 
         
		 return (this.getIdModalidade()==castOther.getIdModalidade())
 && (this.getIdAluno()==castOther.getIdAluno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdModalidade();
         result = 37 * result + this.getIdAluno();
         return result;
   }   


}


