package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Modalidadescontratadas generated by hbm2java
 */
public class Modalidadescontratadas  implements java.io.Serializable {


     private ModalidadescontratadasId id;
     private Alunos alunos;
     private Modalidades modalidades;
     private Date dataDeContratacao;

    public Modalidadescontratadas() {
    }

    public Modalidadescontratadas(ModalidadescontratadasId id, Alunos alunos, Modalidades modalidades, Date dataDeContratacao) {
       this.id = id;
       this.alunos = alunos;
       this.modalidades = modalidades;
       this.dataDeContratacao = dataDeContratacao;
    }
   
    public ModalidadescontratadasId getId() {
        return this.id;
    }
    
    public void setId(ModalidadescontratadasId id) {
        this.id = id;
    }
    public Alunos getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Alunos alunos) {
        this.alunos = alunos;
    }
    public Modalidades getModalidades() {
        return this.modalidades;
    }
    
    public void setModalidades(Modalidades modalidades) {
        this.modalidades = modalidades;
    }
    public Date getDataDeContratacao() {
        return this.dataDeContratacao;
    }
    
    public void setDataDeContratacao(Date dataDeContratacao) {
        this.dataDeContratacao = dataDeContratacao;
    }




}


