package model;

// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Modalidades generated by hbm2java
 */
public class Modalidades implements java.io.Serializable {

	private Integer idModalidade;
	private Statusgeral statusgeral;
	private String descricaoModalidade;
	private Set<Modalidadescontratadas> modalidadescontratadases = new HashSet<Modalidadescontratadas>(
			0);

	public Modalidades() {
	}

	public Modalidades(Statusgeral statusgeral, String descricaoModalidade) {
		this.statusgeral = statusgeral;
		this.descricaoModalidade = descricaoModalidade;
	}

	public Modalidades(Statusgeral statusgeral, String descricaoModalidade,
			Set modalidadescontratadases) {
		this.statusgeral = statusgeral;
		this.descricaoModalidade = descricaoModalidade;
		this.modalidadescontratadases = modalidadescontratadases;
	}

	public Integer getIdModalidade() {
		return this.idModalidade;
	}

	public void setIdModalidade(Integer idModalidade) {
		this.idModalidade = idModalidade;
	}

	public Statusgeral getStatusgeral() {
		return this.statusgeral;
	}

	public void setStatusgeral(Statusgeral statusgeral) {
		this.statusgeral = statusgeral;
	}

	public String getDescricaoModalidade() {
		return this.descricaoModalidade;
	}

	public void setDescricaoModalidade(String descricaoModalidade) {
		this.descricaoModalidade = descricaoModalidade;
	}

	public Set getModalidadescontratadases() {
		return this.modalidadescontratadases;
	}

	public void setModalidadescontratadases(Set modalidadescontratadases) {
		this.modalidadescontratadases = modalidadescontratadases;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((descricaoModalidade == null) ? 0 : descricaoModalidade
						.hashCode());
		result = prime * result
				+ ((idModalidade == null) ? 0 : idModalidade.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Modalidades other = (Modalidades) obj;
		if (descricaoModalidade == null) {
			if (other.descricaoModalidade != null) {
				return false;
			}
		} else if (!descricaoModalidade.equals(other.descricaoModalidade)) {
			return false;
		}
		if (idModalidade == null) {
			if (other.idModalidade != null) {
				return false;
			}
		} else if (!idModalidade.equals(other.idModalidade)) {
			return false;
		}
		return true;
	}

	

}
