package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Planos generated by hbm2java
 */
public class Planos  implements java.io.Serializable {


     private Integer idPlano;
     private Statusgeral statusgeral;
     private String planoDescricao;
     private Set alunoses = new HashSet(0);

    public Planos() {
    }

	
    public Planos(String planoDescricao) {
        this.planoDescricao = planoDescricao;
    }
    public Planos(Statusgeral statusgeral, String planoDescricao, Set alunoses) {
       this.statusgeral = statusgeral;
       this.planoDescricao = planoDescricao;
       this.alunoses = alunoses;
    }
   
    public Integer getIdPlano() {
        return this.idPlano;
    }
    
    public void setIdPlano(Integer idPlano) {
        this.idPlano = idPlano;
    }
    public Statusgeral getStatusgeral() {
        return this.statusgeral;
    }
    
    public void setStatusgeral(Statusgeral statusgeral) {
        this.statusgeral = statusgeral;
    }
    public String getPlanoDescricao() {
        return this.planoDescricao;
    }
    
    public void setPlanoDescricao(String planoDescricao) {
        this.planoDescricao = planoDescricao;
    }
    public Set getAlunoses() {
        return this.alunoses;
    }
    
    public void setAlunoses(Set alunoses) {
        this.alunoses = alunoses;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idPlano == null) ? 0 : idPlano.hashCode());
		result = prime * result
				+ ((planoDescricao == null) ? 0 : planoDescricao.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Planos other = (Planos) obj;
		if (idPlano == null) {
			if (other.idPlano != null) {
				return false;
			}
		} else if (!idPlano.equals(other.idPlano)) {
			return false;
		}
		if (planoDescricao == null) {
			if (other.planoDescricao != null) {
				return false;
			}
		} else if (!planoDescricao.equals(other.planoDescricao)) {
			return false;
		}
		return true;
	}

    
    


}


