package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer idProduto;
     private String descricaoProduto;
     private Integer quantidadeEstoque;
     private Double valorUnitario;
     private Set vendasacademias = new HashSet(0);

    public Produtos() {
    }

    public Produtos(String descricaoProduto, Integer quantidadeEstoque, Double valorUnitario, Set vendasacademias) {
       this.descricaoProduto = descricaoProduto;
       this.quantidadeEstoque = quantidadeEstoque;
       this.valorUnitario = valorUnitario;
       this.vendasacademias = vendasacademias;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public String getDescricaoProduto() {
        return this.descricaoProduto;
    }
    
    public void setDescricaoProduto(String descricaoProduto) {
        this.descricaoProduto = descricaoProduto;
    }
    public Integer getQuantidadeEstoque() {
        return this.quantidadeEstoque;
    }
    
    public void setQuantidadeEstoque(Integer quantidadeEstoque) {
        this.quantidadeEstoque = quantidadeEstoque;
    }
    public Double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public Set getVendasacademias() {
        return this.vendasacademias;
    }
    
    public void setVendasacademias(Set vendasacademias) {
        this.vendasacademias = vendasacademias;
    }




}


