package model;
// Generated 03/01/2016 21:12:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VendasacademiaId generated by hbm2java
 */
public class VendasacademiaId  implements java.io.Serializable {


     private int idVenda;
     private Date dataDaVenda;

    public VendasacademiaId() {
    }

    public VendasacademiaId(int idVenda, Date dataDaVenda) {
       this.idVenda = idVenda;
       this.dataDaVenda = dataDaVenda;
    }
   
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }
    public Date getDataDaVenda() {
        return this.dataDaVenda;
    }
    
    public void setDataDaVenda(Date dataDaVenda) {
        this.dataDaVenda = dataDaVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendasacademiaId) ) return false;
		 VendasacademiaId castOther = ( VendasacademiaId ) other; 
         
		 return (this.getIdVenda()==castOther.getIdVenda())
 && ( (this.getDataDaVenda()==castOther.getDataDaVenda()) || ( this.getDataDaVenda()!=null && castOther.getDataDaVenda()!=null && this.getDataDaVenda().equals(castOther.getDataDaVenda()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVenda();
         result = 37 * result + ( getDataDaVenda() == null ? 0 : this.getDataDaVenda().hashCode() );
         return result;
   }   


}


